parameters:
#    ing_unibo_scambi.example.class: IngUnibo\Bundle\ScambiBundle\Example

services:
#    ing_unibo_scambi.example:
#        class: %ing_unibo_scambi.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
